from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

questions = [
    "My memory for this event is clear.",
    "My memory for this event is very vivid.",
    "My memory for this event is very detailed.",
    "My memory for this event is dim.",
    "My memory for this event is very vague.",
    "My memory for this event is sketchy.",
    "The order of events in the memory is clear.",
    "When I recall this memory, the sequence of events seems realistic.",
    "This memory is of an event that occurred once at a particular time and place, not a summary or merging of many similar or related events.",
    "I recognize the setting in which my memory takes place.",
    "The order of events in the memory is confusing. ",
    "This memory comes back to me in bits and pieces, not as a logical, coherent story. ",
    "This memory is a blending of many similar, related events rather than a specific memory about a particular event.",
    "I have a difficult time remembering the event in a coherent manner.",
    "This memory just sprang to my mind when I read the instructions.",
    "This memory was easy for me to recall.",
    "It was difficult for me to think of this memory.",
    "I had to think for a while before I could recall this event.",
    "I really had to search my ‘‘memory bank’’ for this experience.",
    "As I remember the event, I can hear it in my mind.",
    "As I remember the event, I can feel now the emotions that I felt then.",
    "I can bodily ‘‘feel’’ myself in this memory.",
    "When I recall this event, I think the same things I thought when the event originally happened.",
    "When I recall this memory, I do not feel the same feelings I felt when the event originally happened.",
    "When I recall this event, it does not really feel like I am reliving the experience.",
    "My memory for this event does not involve a lot of sensory information (sounds, smells, tastes, etc.).",
    "As I remember the event, I have a difficult time recalling the particular physical reactions and sensations I had during the experience.",
    "As I am remembering the experience now, my feelings are very intense.",
    "My emotions are very intense concerning this event.",
    "The memory of this event evokes powerful emotions.",
    "I do not remember having particularly strong emotions at the time of this event.",
    "I do not have strong emotions about this memory.",
    "This memory does not evoke strong emotions in me.",
    "I see the experience in the memory through my own eyes.",
    "In my memory, I see this experience through my own eyes.",
    "When I visualize this memory, I clearly see this event from my own perspective.",
    "I view this memory as if I was an observer to the experience.",
    "In my memory, I see this experience through the eyes of others.",
    "As I remember this event, I feel like an observer watching myself.",
    "My memory for the year when the event took place is clear.",
    "My memory for the day when the event took place is clear.",
    "My memory for the hour when the event took place is clear.",
    "My memory for the year when the event took place is vague.",
    "My memory for the day when the event took place is vague.",
    "My memory for the hour when the event took place is vague.",
    "I often share this memory with friends or family.",
    "Since it happened, I have talked about this event many times.",
    "I frequently think about or talk about this event with others.",
    "I rarely tell others about this memory.",
    "I do not feel the need to share this memory with others.",
    "I do not think about this memory often.",
    "I don’t have much in common with the person in the memory.",
    "I feel like the person in this memory is a different person than who I am today.",
    "When I recall this memory, I think, 'that’s not me anymore.'",
    "My behaviour in this memory is consistent with my personality.",
    "I feel like I am the same person in the memory as I am today.",
    "This memory is consistent with who I think I am today.",
    "The overall tone of the memory is positive.",
    "The experience described in this memory is positive.",
    "My feelings at the time were positive.",
    "The overall tone of the memory is negative.",
    "The experience described in this memory is negative.",
    "My feelings at the time were negative.",
    "As I remember the event, I feel as though I am reliving the original event.",
    "As I remember the event, I can hear it in my mind.",
    "As I remember the event, I can see it in my mind.",
    "As I remember the event, I or other people are talking.",
    "As I remember the event, I know its spatial layout.",
    "As I remember the event, I can feel now the emotions that I felt then.",
    "As I remember the event, I can recall the setting where it occurred.",
    "Sometimes people know something happened to them without being able to actually remember it. As I think about the event, I can actually remember it rather than just knowing that it happened.",
    "As I remember the event, it comes to me in words.",
    "As I remember the event, I feel that I travel back to the time when it happened, that I am a subject in it again, rather than an outside observer tied to the present. ",
    "As I remember the event, it comes to me in words or in pictures as a coherent story or episode and not as an isolated fact, observation, or scene.",
    "This memory is significant for my life because it imparts an important message for me or represents an anchor, critical juncture, or a turning point.",
    "Would you be confident enough in your memory of the event to testify in a court of law.",
    "I believe the event in my memory really occurred in the way I remember it and that I have not imagined or fabricated anything that did not occur.",
    "Since it happened, I have thought or talked about this event.",
    "If another witness to the event, who you generally trusted, existed and told you a very different account of the event to what extent could you be persuaded that your memory was wrong.",
    "To the best of your knowledge, is the memory of an event that occurred once at one particular time and place, a summary or merging of many similar or related events, or for events that occurred over a fairly continuous extended period of time lasting more than a day?",
    "Please date the memory (month/day/year) as accurately as you can. Please fill in a month, day, and year even if you must estimate. If the memory extended over a period of time, report the approximate middle of the period.",
    "To what extent is your memory of the event distorted by your beliefs, motives, and expectations rather than an accurate reflection of the event as a neutral observer would report it?",
    "While remembering the event, I feel as though I am reliving it.",
    "While remembering the event, it comes to me in words or in pictures as a coherent story or episode and not as an isolated fact, observation, or scene.",
    "While remembering the event, I feel that I see it out of my own eyes rather than that of an outside observer.",
    "My memory comes in pieces with missing bits.",
    "While remembering the event, I feel the same particular emotions I felt at the time of the event.",
    "While remembering the event, I feel the emotions as strongly as I did then.",
    "While remembering the event, the emotions are extremely positive.",
    "While remembering the event, the emotions are extremely negative.",
    "The emotions that I feel are extremely intense.",
    "While remembering the event, I feel my heart pound, or race.",
    "While remembering the event, I feel sweaty or clammy.",
    "While remembering the event, I feel tense all over or I feel knots, cramps, or butterflies in my stomach.",
    "While remembering the event, I can see it in my mind.",
    "While remembering the event, I can hear it in my mind.",
    "While remembering the event, I know the setting where it occurred.",
    "While remembering the event, I feel that I travel back to the time when it happened.",
    "My memory is based on details specific to my life, not on general knowledge that I would expect most people to have.",
    "While remembering the event, it comes to me in words.",
    "As I think about the event, I can actually remember it rather than just knowing that it happened.",
    "Since it happened, I have thought or talked about this event.",
    "This memory has previously come to me “out of the blue,” without my trying to think about it.",
    "I believe the event in my memory really occurred in the way I remember it and that I have not imagined or fabricated anything that did not occur.",
    "How old are you in this memory?",
    "While remembering the event, I can see it in my mind.",
    "I see it out of my own eyes rather than those of an outside observer.",
    "While remembering the event, I know the setting where it occurred.",
    "While remembering the event, I can hear it in my mind.",
    "While remembering the event, I can smell it.",
    "While remembering, the emotions are extremely negative or positive.",
    "While remembering, the emotions that I feel are extremely intense.",
    "I had a physical reaction (laughed, felt tense, sweaty, heart pound).",
    "The memory changed my mood.",
    "While remembering the event, It comes to me in words.",
    "It comes to me in words or in pictures as a coherent story.",
    "It comes to me in words or in pictures as a coherent story.",
    "The event in my memory is a central part of my life story.",
    "Since it happened, I have thought or talked about this event.",
    "This memory has come to me out of the blue, without my trying.",
    "The event occurred once at one particular time (within a day) and place.",
    "A merging of events versus a longer continuous extended event.",
    "Please date the memory (month/day/year) [calculated from test date].",
    "Was this memory cued by the environment, thoughts, a mix, or voluntary.",
    "The event is related to or about one of the three stressful events I listed.",
    "While remembering the event, I feel as though I am reliving it.",
    "I believe the event in my memory really occurred – not imagined.",
    "Since it happened, I have thought or talked about this event.",
    "When remembering the event, do you see the event through your own eyes.",
    "When remembering the event, do you see the event as an outside observer.",
    "While remembering the event, I can see it in my mind.",
    "While remembering the event, I can hear it in my mind.",
    "While remembering the event, I feel that I travel back to the time when it happened.",
    "As I think about the event, I can actually remember it rather than just knowing that it happened.",
    "While remembering the event, I feel as though I am reliving it.",
    "I believe the event in my memory really occurred in the way I remember it and that I have not imagined or fabricated anything that did not occur.",
    "If another witness to the event, who you generally trusted, existed and told you a very different account of the event, to what extent could you be persuaded that your memory of the event was wrong.",
    "While remembering the event, I feel the emotions as strongly as I did then.",
    "While remembering the event, the emotions are extremely positive.",
    "While remembering the event, the emotions are extremely negative.",
    "The emotions that I feel are extremely intense.",
    "While remembering, it is as if I am living the occurrence again.",
    "While remembering, it is as if I am mentally traveling back to the time and place of the occurrence.",
    "While remembering, it is as if I am experiencing the same feelings, emotions, and/or atmosphere again.",
    "While remembering, I can see everything in my mind.",
    "While remembering, the actions, objects, and/or people that are involved in the memory are as clear now as they were when the event occurred.",
    "I believe the event in my memory really occurred in the way I remember it and that I have not imagined or fabricated anything that did not occur.",
    "My memory of the event is an accurate reflection of the event as a neutral observer would report it and is not distorted by my beliefs, motives, and expectations.",
    "Would you be confident enough in your memory of the event to testify in a court of law?",
    "While remembering, I experience a scene in which the elements of the setting are located relative to each other in space.",
    "As I remember, I can describe where the actions, objects, and/or people are located in the memory.",
    "While remembering, I can identify or name the setting where the memory occurred, although I might not be able to describe it clearly.",
    "As I remember, I can identify the actions, objects, and/or people that are involved in the memory, though I may not be able to clearly say where they are in relation to each other.",
    "While remembering, I can identify where I am in relation to the things that I am remembering.",
    "While remembering, I see the memory from where I was during the event, that is, as if I was seeing it again from my own eyes at my original location.",
    "While remembering, I see the memory from a different location than the one I was at in the event, that is, as if I was remembering a new view of the same event as an outside observer.",
    "How positive or negative is this memory?",
    "While remembering, the emotions I feel are intense.",
    "When did this memory originally occur?",
    "Is the memory of a merging of many versions of a general repetitive event, or is it a unique event that occurred only once?",
    "Did the event appear to happen once at one particular time and place, or was it a summary or merging of related events, or did it occur over a fairly continuous extended period of time lasting more than a day?",
    "The memory is of a general situation that happened many times in my life, rather than of a specific occurrence with its own details that let me know the memory was of a single event. ",
    "While remembering, it is as if I am reliving the event.",
    "I believe the event in my memory really occurred in the way I remember it and that I have not imagined or fabricated anything that did not occur.",
    "While remembering the event, the emotions that I feel are extremely intense.",
    "My memory of the event is vivid.",
    "Was the memory for an event that occurred once and lasted less than a day or was the event extended in time for more than a day, possibly being made up of several related events.",
    "While remembering, the event it is as if I am mentally traveling back to the time it occurred.",
    "My memory of the event is an accurate reflection of the event as a neutral observer would report it and is not distorted by my beliefs, motives, and expectations.",
    "While remembering the event, I have a physical reaction (laughed, felt tense, sweaty, heart pounded).",
    "My memory event has lots of details.",
    "ow long did the event last?",
    "While remembering the event, it is as if I am experiencing the same general atmosphere again.",
    "I would be confident enough in my memory of the event to testify in a court of law.",
    "While remembering the event, my emotions are negative or positive.",
    "My memory of the event is clear, not fuzzy or clouded.",
    "Could the event theoretically be dated to one specific day in your past, even though you might not be able to date it?",
    "Where were you when the memory came to mind?",
    "What were you doing when the memory came to mind?",
    "Did you think of something else while you were doing this?",
    "Was your attention concentrated on certain tasks or thoughts?",
    "How was your mood just before the memory came to mind?",
    "Describe the situation in which the memory came to mind.",
    "Describe the memory.",
    "Compare the content of the memory with what had taken place in your thoughts and surroundings right before the memory came to your mind. Did anything in your surroundings or activities or anything in your thoughts or on your mind repeat itself in the memory? Check the commonalities which stand out (people / places / sensory experiences / objects / feelings / life themes / activities / wording / no commonali ties / other).",
    "Were the commonalities present in your physical surroundings (i.e. external) or only present in your thoughts (i.e. internal) or both places (i.e. mixed)?",
    "Does this memory refer to a specific event in your past?",
    "How vivid is the memory?",
    "Did the memory affect your mood?",
    "What is your location in the memory?",
    "Did you physically react in response to the memory (i.e. talking to yourself, smiling, crying, shivering, laughing etc.) (yes/ no response), if yes, describe.",
    "Have you previously thought about this memory?",
    "Is this memory central to your identity?",
    "Does this memory refer to an important event in your life?",
    "How do you remember your emotions at the time of the event?",
    "How old is the memory? (today or yesterday / yesterday to one week / one week to two weeks / two weeks to one month / one month to six months / six months to one year / one year to five years / five years ago).",
    "How old were you when the event happened?",
    "Is this one of those memories you try to avoid thinking about?",
    "When these memories occurred to me, I wondered 'Why do I always behave this way'? or 'Why did this event happen to me'?",
    "When this memory occurred to me, I was worried that it might happen again.",
    "When this memory occurred to me, I thought 'I can’t handle this problem' or 'I might have mental problems' or 'this world is terrible'",
    "When this memory came to my mind, I thought 'I am loved' or 'I am valuable' or 'this world is wonderful'.",
    "This memory reminded me of some solutions to solve similar problems.",
    "I thought more positively about the event happened in the memory.",
    "While remembering, it is as if I am reliving the event.",
    "While remembering, it is as if I am mentally traveling back to the time the event occurred.",
    "My memory of the event is vivid.",
    "My memory of the event has lots of details.",
    "I believe the event in my memory really occurred in the way I remember it and that I have not imagined or fabricated anything that did not occur.",
    "My memory of the event is an accurate reflection that a neutral observer would report.",
    "While remembering the event, I can see it clearly in my mind.",
    "My memory of the event has a clear, detailed visual image.",
    "While remembering the event, I know where I am in relation to the individual things that I am remembering.",
    "While remembering the event, I can describe the layout of things in my memory relative to each other.",
    "While remembering, I know the contents of the memory, but I cannot say where they are in relation to each other.",
    "While remembering, I can imagine the individual details, but they do not all fit together as a coherent scene.",
    "My memory of the event is for a specific moment in my life. It is not for a blending of several similar situations.",
    "The event in my memory could be dated to one specific day in my past, even though I might not be able to date it.",
    "While remembering the event, I can hear it clearly in my mind.",
    "My memory of the event has clear, detailed sounds.",
    "My memory of the event is a good story or description.",
    "My memory of the event comes to me a coherent and connected narrative.",
    "My memory of the event has become a reference point for the way I understand myself and the world.",
    "My memory of the event has become a part of my life story.",
    "I often think about my memory of the event.",
    "My memory of the event often enters my thoughts without me trying to remember it.",
    "While remembering the event, the emotions that I feel are extremely intense.",
    "While remembering the event, I have a physical reaction (laugh, feel tense, sweaty, heart pounds).",
    "My memories of past events have lots of details.",#ART
    "My memories of past events come to me as good stories or descriptions.",
    "While remembering past events, it is as if I am reliving them.",
    "I often think back to past events in my mind and think or talk about them.",
    "In my memories of past events, I remember where the actions, objects, and people are located in the events.",
    "While remembering past events, I can see them in my mind.",
    "My memories of past events are a central part of my life story.",
    "My memories of past events are vivid.",
    "My memories of past events are coherent and connected, not a collection of isolated, disconnected fragments.",
    "While remembering past events, it is as if I am mentally traveling back to the time they occurred.",
    "My memories of past events often pop into my mind by themselves--without me consciously trying to remember them.",
    "In my memories of past events, I remember where I am in relation to the individual things in the events.",
    "While remembering past events, I can see with my mind's eye what took place.",
    "My memories of past events are part of my identity.",
    "My memories of past events are clear, not fuzzy or clouded.",
    "My memories of past events come to me complete, not in pieces with missing bits.",
    "While remembering past events, it is as if I am experiencing the same general atmosphere again.",
    "After an event has happened, I often willfully and deliberately think back to it in my mind and try to remember it.",
    "In my memories of past events, I remember the layout of the broader setting in which the events are located.",
    "My memories of past events have clear visual details.",
    "My memories of past events are a reference point for the way I understand myself and the world.",
    "Specific events are difficult for me to recall.",#SAM
    "When I remember events, I have a hard time determining the order of details in the event.",
    "When I remember events, in general I can recall objects that were in the environment.",
    "When I remember events, in general I can recall what I was wearing.",
    "I am highly confident in my ability to remember past events.",
    "When I remember events, I remember a lot of details.",
    "When I remember events, in general I can recall which day of the week it was.",
    "When I remember events, in general I can recall people, what they looked like, or what they were wearing.",
    "I can learn and repeat facts easily, even if I don’t remember where I learned them.",
    "After I have read a novel or newspaper, I forget the facts after a few days.",
    "After I have met someone once, I easily remember his or her name.",
    "I can easily remember the names of famous people (sports figures, politicians, celebrities).",
    "I have a hard time remembering information I have learned at school or work.",
    "I am very good at remembering information about people that I know (e.g., the names of a co-worker’s children, their personalities, places friends have visited etc.).",
    "In general, my ability to navigate is better than most of my family/friends.",
    "After I have visited an area, it is easy for me to find my way around the second time I visit.",
    "I have a hard time judging the distance (e.g., in meters or kilometers) between familiar landmarks.",
    "I get lost easily, even in familiar areas.",
    "If my route to work or school was blocked, I could easily find the next fastest way to get there.",
    "I use specific landmarks for navigating.",
    "When I imagine an event in the future, the event generates vivid mental images that are specific in time and place.",
    "When I imagine an event in the future, I can picture the spatial layout.",
    "When I imagine an event in the future, I can picture people and what they look like.",
    "When I imagine an event in the future, I can imagine how I may feel.",
    "When I imagine an event in the future, I can picture images (e.g., people, objects, etc).",
    "I have a difficult time imagining specific events in the future.",
    "I remember the event vividly.",#AMCQ
    "I remember the event very clearly.",
    "The things I experienced during the event are so vivid that I feel as though it just happened yesterday.",
    "I can remember the situation in which the event occurred vividly, as though I were there.",
    "If I asked, I could make a film about the event that would depict exactly what happened, because I remember it so clearly.",
    "My memory of this event is very detailed.",
    "My memory of this event is very vague.",
    "I have a dim recollection of this event.",
    "I think that the event may have occurred differently to how I remember it.",
    "I am seriously doubtful that the event occurred in the way I remember it.",
    "The event occurred exactly the way I remember it.",
    "As I remember the event, I have not imagined or fabricated anything that did not occur.",
    "I am sure that the event occurred in the way I remember it.",
    "I can remember the city in which the event took place.",
    "I can remember the district in which the event took place.",
    "I can remember the country in which the event took place.",
    "I can remember the room (if the event took place inside) or to within a few meters (if the event took place outside).",
    "I can remember details of the place (such as the location or name of the place) where the event took place.",
    "I can remember my body position or my posture or how I acted during the event.",
    "As I remember this event, I can see the details or the colours of the things related to the event (such as the furniture or the wallpaper).",
    "I can remember tactile details (such as temperature or pain) about the event.",
    "As I remember this event, I can sense the odour (such as damp or perfume of someone close to you) surrounding the event.",
    "As I remember this event, I can hear the sounds that I heard during the event in my mind.",
    "My memory of this event does not involve any sensory information (sound, smell, taste, etc.).",
    "I had to search my memory to recall this event.",
    "I had to think for a while to recall this event.",
    "I do not recall this event very often.",
    "Since this event took place, I have thought or talked about it.",
    "This memory came spontaneously to my mind while I was reading the instructions.",
    "It is easy for me to recall this memory.",
    "I find myself remembering this event while I am thinking about something else.",
    "I often share this memory with others.",
    "I often talk about this event with my friends or family.",
    "Since it happened, I have talked about this event with others many times.",
    "I have not talked about the event with others.",
    "I do not share this memory with others.",
    "As I remember the event, I feel as though I am seeing the event as an outside observer.",
    "As I remember the event, I feel as though I am watching a short film about someone else.",
    "As I remember the event, I feel as though I am looking at the past me and others around me from above or far away.",
    "As I remember the event, I imagine it again through my own eyes.",
    "I view this memory through my own eyes, from my own perspective.",
    "As I remember the event, I feel as though I am seeing the event out of my own eyes rather than as an outside observer.",
    "This memory comes back to me in disjointed pieces.",
    "This memory comes back to me in disjointed flashbacks.",
    "As I remember the event, there are gaps and some things I cannot remember in the storyline.",
    "The order of events in the memory is incoherent and confusing.",
    "I remember the event in chronological order (before, during and after).",
    "As I remember the event, the memory comes to my mind in words or pictures as a complete and coherent story.",
    "As I remember the event, a number of things that are unrelated to the event also come to mind.",
    "As I remember the event, I feel as though I am travelling to the time it happened.",
    "As I remember the event, I feel as though I travelled back and become the same person in the event.",
    "As I remember the event, I feel as though I am reliving it.",
    "As I remember the event, I feel as if I am thinking the same things or feeling the same emotions as I did during the event.",
    "As I think about the event, I actually remember it rather than just knowing that it happened.",
    "I feel as though this memory is of an event that was experienced by a person other than me .",
    "The experience I recall is quite negative.",
    "The experience I recall is quite positive.",
    "My feelings at the time of the event were quite negative.",
    "My overall feeling about the event is quite negative.",
    "My feelings at the time of the event were quite positive.",
    "My overall feeling about the event is quite positive.",
    "While remembering the event now, my feelings are quite weak.",
    "While remembering the event now, my feelings are quite intense.",
    "My memory of this event evokes very weak emotions in me.",
    "When I focus the event, I feel very intense emotions.",
    "My memory of this event evokes very strong emotions in me.",
    "When I focus on the event, I don’t feel much of anything.",
    "As I remember the event, I bottle up my feelings.",
    "While talking about this event, I relate what happened rather than what I felt or thought.",
    "As I remember the event, I smother my feelings.",
    "As I remember the event, although my feelings are important to me, I prefer to ignore them.",
    "As I remember the event, if what I felt at the time of the event comes to my mind, I try to think about something else.",
    "As I think or talk about the event, I can be open about my feelings.",
    "As I think or talk about the event, I feel comfortable.",
    "As I talk about the event, I let others understand my feelings.",
    "This event is still difficult to think about because of the feelings that the memory evokes.",
    "As I remember the event, my feelings are so intense that I cannot focus on any activity after that.",
    "As I remember the event, I feel lost in my thoughts because of my feelings.",
    "While talking about this event, I feel such an intense need to share my feelings that I cannot tell the event as a coherent story.",
    "As I remember the event, I cannot focus on anything except my feelings.",
    "As I remember the event, my feelings confuse me.",
    "I feel comfortable going through my feelings about this event.",
    "As I remember the event, focusing on my feelings never influences me.",
    "I can remember the date as day/month/year in which the event took place.",
    "I can remember the period (such as during university times or in my 20s) in which the event took place.",
    "I can remember the season in which the event took place.",
    "I can remember the time of day (such as morning) when the event took place.",
    "As I remember the event, I feel the emotions as strongly as I did at the time of the event.",
    "As I remember the event, I feel the same emotions as I did at the time of the event.",
    "My feelings at the time of the event never change over time.",
    "My feelings at the time of the event become weaker over time.",
    "I no longer feel the same emotions as I did at the time of the event.",
    "My feelings at the time of the event have changed over time.",
    "As I remember the event, I feel my heart pounds or races.",
    "As I remember the event, I feel my hands shaking.",
    "As I remember the event, I feel sweaty.",
    "As I remember the event, I feel cramps or butterflies in my stomach.",
    "As I remember the event, I feel my knees shaking.",
    "As I remember the event, I feel headaches or giddiness.",
    "This event is very important to me.",
    "This event has serious implications in my life.",
    "I learned a lot from this event, which makes me a different person.",
    "This event was a turning point in my life; I can divide my life story into before and after the event happened.",
    "This event is not personally important to me.",
    "This event has not changed anything in my life.",
    "As I remember the event, I feel as though I am reliving the original event.",#MCQ
    "As I remember the event, I can hear it in my mind.",
    "As I remember the event, I can see it in my mind.",
    "As I remember the event, I or other people are talking.",
    "As I remember the event, I know its spatial layout.",
    "As I remember the event, I can feel now the emotions that I felt then.",
    "As I remember the event, I can recall the setting where it occurred.",
    "Sometimes people know something happened to them without being able to actually remember it. As I think about the event, I can actually remember it rather than just knowing that it happened.",
    "As I remember the event, it comes to me in words.",
    "As I remember the event, I feel that I travel back to the time when it happened, that I am a subject in it again, rather than an outside observer tied to the present.",
    "As I remember the event, it comes to me in words or in pictures as a coherent story or episode and not as an isolated fact, observation, or scene.",
    "As I remember the event, I imagine it again through my own eyes seeing what I would have seen then, or as an observer from a different   perspective than the one I had.",
    "I believe the event in my memory really occurred in the way I remember it and that I have not imagined or fabricated anything that did not occur.",
    "Since it happened, I have thought or talked about this event."
]

# 加载模型
model = SentenceTransformer('all-MiniLM-L6-v2')

# 转换为向量（每个句子 -> 一个向量）
embeddings = model.encode(questions)

# 查看结果（每个向量是384维）
print(f"Shape: {embeddings.shape}")  # 应为 (题目数量, 384)

# 打印所有向量的形状
print(f"All embeddings shape: {embeddings.shape}")

from sklearn.metrics.pairwise import cosine_similarity

# 已经有题目向量 embeddings
similarity_matrix = cosine_similarity(embeddings)

#计算总体相似度
# 去除对角线（每题与自己相似度 = 1，不计入平均）
n = similarity_matrix.shape[0]
mask = ~np.eye(n, dtype=bool)  # 创建一个 n×n 的布尔矩阵，对角线为 False，其他为 True
mean_similarity = similarity_matrix[mask].mean()

print(f"平均题目余弦相似度（排除对角线）: {mean_similarity:.4f}")


#计算两两之间相似度
# 计算余弦相似度矩阵
similarity_matrix = cosine_similarity(embeddings)

# 设置批量写入大小
batch_size = 100
counter = 0

# 将结果写入文件
with open("cosine_similarities.txt", "w") as f:
    for i in range(similarity_matrix.shape[0]):
        for j in range(i+1, similarity_matrix.shape[1]):
            f.write(f"Cosine similarity between question {i+1} and question {j+1}: {similarity_matrix[i][j]:.4f}\n")
            counter += 1
            if counter % batch_size == 0:
                print(f"{counter} pairs written to file...")

# 打印完成提示
print("All pairwise cosine similarities have been saved to 'cosine_similarities.txt'.")

pca = PCA()
pca.fit(embeddings)
explained_var = np.cumsum(pca.explained_variance_ratio_)

# 打印每个维度下累计解释方差
for i, var in enumerate(explained_var):
    print(f"维度 {i+1}: 累计解释方差 = {var:.4f}")
    if var >= 0.90:
        print(f"\n✅ 推荐维数：{i+1}（可解释 90% 的总方差）")
        break

